{% set name = "python-mistralclient" %}
{% set version = "4.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-mistralclient-{{ version }}.tar.gz
  sha256: d0aa05f1751cba6f906d7c8053ff41da14dc83a98291ddda574b3ea93b5d4b20

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mistral = mistralclient.shell:main

requirements:
  host:
    - pbr >=2.0.0
    - pip
    - python >=3.6
  run:
    - cliff !=2.9.0,>=2.8.0
    - keystoneauth1 >=3.4.0
    - osc-lib >=1.8.0
    - oslo.i18n >=3.15.3
    - oslo.serialization !=2.19.1,>=2.18.0
    - oslo.utils >=3.33.0
    - pbr !=2.1.0,>=2.0.0
    - python >=3.6
    - pyyaml >=3.13
    - requests >=2.14.2
    - stevedore >=1.20.0

test:
  imports:
    - mistralclient
  commands:
    - pip check
    - mistral -h
  requires:
    - pip

about:
  home: https://docs.openstack.org/python-mistralclient/latest/
  summary: Mistral Client Library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
